### ISSUE TITLE
Better reporting when connections die

### ISSUE THREAD

**Issue by chelm** [timbr-io/juno-magic#4]
A few things need to be cleaned up with how users are informed about the current state of a juno connection. The most pressing is the error info:

```
Unhandled error in Deferred:
...
 File "/Users/chelm/dev/timbr/juno-magic/juno_magic/extensions/wamp.py", line 320, in execute
    yield self._wamp.set_prefix(prefix)
exceptions.TypeError: sequence item 0: expected string, NoneType found
```

I think we just need to be checking for `wamp is not None` and/or handling this exception in order to print out something useful to users

**Comment by chelm** [comment]
One thing about this is when I connect, list, and then try to run a `%%juno` command BEFORE `%juno select ...` i get a gnarly error that could be more helpful like 'No kernel currently selected...did you run juno select yada yada'

**Comment by pramukta** [comment]
On-demand connection and some better error messages address this for now.  May need to revisit later
